# Generated by Django 4.0.1 on 2024-02-11 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0002_alter_asistencia_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
