# Generated by Django 4.0.1 on 2024-02-15 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0003_asistencia_hora_entrada_asistencia_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
