# Generated by Django 4.0.1 on 2024-02-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0004_alter_asistencia_fecha_alter_asistencia_hora_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardUser.asistencia')),
            ],
        ),
    ]
