# Generated by Django 4.0.1 on 2024-02-23 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0006_asistencia_tarea1_asistencia_tarea2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
