# Generated by Django 4.0.1 on 2024-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0008_asistencia_hora_marcada'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='responsabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tarea1',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tarea2',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tarea3',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tarea4',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tarea5',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='actividades_valor',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardUser.actividades_valor'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='metas',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardUser.metas'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='responsabilidades',
            field=models.ManyToManyField(blank=True, null=True, to='DashboardUser.responsabilidades'),
        ),
    ]
