# Generated by Django 4.0.1 on 2024-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0009_actividades_valor_metas_responsabilidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='actividades_valor',
            field=models.ManyToManyField(blank=True, to='DashboardUser.actividades_valor'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='metas',
            field=models.ManyToManyField(blank=True, to='DashboardUser.metas'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='responsabilidades',
            field=models.ManyToManyField(blank=True, to='DashboardUser.responsabilidades'),
        ),
    ]
