# Generated by Django 4.0.1 on 2024-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0010_alter_asistencia_actividades_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='actividades_valor',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='actividades_valor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='metas',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='metas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='responsabilidades',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='responsabilidades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
