# Generated by Django 4.0.1 on 2024-03-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0011_remove_asistencia_actividades_valor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actividades_valor',
        ),
        migrations.DeleteModel(
            name='metas',
        ),
        migrations.DeleteModel(
            name='responsabilidades',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_entrada',
        ),
    ]
