# Generated by Django 4.0.1 on 2024-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0012_delete_actividades_valor_delete_metas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='actividades_valor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='metas',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='responsabilidades',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
