# Generated by Django 4.0.1 on 2024-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0013_asistencia_evidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='evidencia',
            field=models.ImageField(upload_to='evidencias/'),
        ),
    ]
