# Generated by Django 4.0.1 on 2024-03-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0014_alter_asistencia_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_marcada',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
