# Generated by Django 4.0.1 on 2024-03-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0015_alter_asistencia_hora_marcada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='puntuacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
