# Generated by Django 4.0.1 on 2024-03-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0017_remove_asistencia_presente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='metas',
            new_name='logros',
        ),
    ]
