# Generated by Django 4.0.1 on 2024-03-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0018_rename_metas_asistencia_logros'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
