# Generated by Django 4.0.1 on 2024-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0020_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='hora_salida',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
