# Generated by Django 4.2.2 on 2024-06-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0021_horario_hora_salida'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='asistencia',
          #  name='logros',
        #),
    ]
