# Generated by Django 4.0.1 on 2024-01-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0002_alter_empleado_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
