# Generated by Django 4.0.1 on 2024-01-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0003_alter_empleado_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
