# Generated by Django 4.0.1 on 2024-01-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0008_remove_recurso_cantidad_remove_recurso_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
