# Generated by Django 4.0.1 on 2024-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0010_categoriainventario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
