# Generated by Django 4.0.1 on 2024-03-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0013_empresa_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='productos',
            field=models.ManyToManyField(to='DashboardAdmin.Producto'),
        ),
    ]
