# Generated by Django 4.0.1 on 2024-03-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0014_remove_inventario_producto_inventario_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inventarios',
            field=models.ManyToManyField(related_name='productos', through='DashboardAdmin.Inventario', to='DashboardAdmin.Empresa'),
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='productos',
        ),
        migrations.AddField(
            model_name='inventario',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.producto'),
            preserve_default=False,
        ),
    ]
