# Generated by Django 4.0.1 on 2024-03-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0018_inventario_productos_remove_producto_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='productos',
        ),
        migrations.AlterField(
            model_name='producto',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='DashboardAdmin.inventario'),
        ),
    ]
