# Generated by Django 4.0.1 on 2024-03-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0020_alter_producto_descripcion_local_inventario_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='direccion',
        ),
    ]
