# Generated by Django 4.0.1 on 2024-03-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0022_producto_local'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Sucursal',
        ),
    ]
