# Generated by Django 4.0.1 on 2024-03-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0023_rename_empresa_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='local',
        ),
    ]
