# Generated by Django 4.0.1 on 2024-03-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0024_remove_inventario_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
