# Generated by Django 4.0.1 on 2024-03-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0025_remove_empleado_direccion_remove_empleado_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='salario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
