# Generated by Django 4.0.1 on 2024-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0026_remove_cargo_salario_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='DNI',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
