# Generated by Django 4.0.1 on 2024-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0027_empleado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/'),
        ),
    ]
