# Generated by Django 4.0.1 on 2024-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0028_alter_empleado_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fondos/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='frase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
