# Generated by Django 4.0.1 on 2024-03-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0029_empleado_alias_empleado_fondo_empleado_frase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
        migrations.AddField(
            model_name='producto',
            name='surucsal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='DashboardAdmin.sucursal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
