# Generated by Django 4.0.1 on 2024-03-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0030_remove_producto_inventario_producto_surucsal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='surucsal',
            new_name='sucursal',
        ),
    ]
