# Generated by Django 4.0.1 on 2024-03-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0031_rename_surucsal_producto_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(auto_now_add=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now_add=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.producto')),
            ],
        ),
    ]
