# Generated by Django 4.0.1 on 2024-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0032_registrosalida_registroentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalida',
            name='producto',
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='productos',
            field=models.ManyToManyField(to='DashboardAdmin.Producto'),
        ),
    ]
