# Generated by Django 4.0.1 on 2024-03-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0033_remove_registrosalida_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalida',
            name='ganacias',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='motivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
