# Generated by Django 4.0.1 on 2024-03-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0034_registrosalida_ganacias_registrosalida_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosalida',
            name='productos',
        ),
        migrations.AddField(
            model_name='registrosalida',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardAdmin.producto'),
            preserve_default=False,
        ),
    ]
