# Generated by Django 4.0.1 on 2024-04-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0035_remove_registrosalida_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='ganacias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
