# Generated by Django 3.2.16 on 2024-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardAdmin', '0037_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
